name: CI/CD Pipeline
permissions:
  contents: write

on:
  push:
    branches: [main, qa]
  pull_request:
    branches: [main, qa]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install static server
        run: npm install -g serve
      - name: Serve production-site locally
        run: nohup serve -l 3000 production-site &
      - name: Wait for local server to be ready
        run: |
          for i in {1..10}; do
            nc -z localhost 3000 && echo 'Server is up!' && break
            echo 'Waiting for server...'
            sleep 2
          done
      - name: Run Playwright tests (local)
        run: npx playwright test
        env:
          BASE_URL: http://localhost:3000
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: List production-site contents
        run: ls -l production-site
      - name: Deploy to GitHub Pages (Production)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./production-site
          publish_branch: gh-pages

  deploy-qa:
    if: github.ref == 'refs/heads/qa'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Make Playwright CLI executable
        run: chmod +x node_modules/.bin/playwright
      - name: Debug Playwright CLI permissions
        run: ls -l node_modules/.bin/playwright
      - name: Run Playwright tests (QA)
        run: npx playwright test
        env:
          BASE_URL: https://Padraic79.github.io/ProductionReadyCI-CD/
      - name: Deploy to Github Pages (QA)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./qa-site
          publish_branch: gh-pages-qa
